name: Bulk Mark Inactive Approved

on:
  issues:
    types: ["labeled"]

concurrency: add_internships

jobs:
  run-bulk-mark-inactive:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'approved' && contains(github.event.issue.labels.*.name, 'bulk_mark_inactive')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: execute bulk_mark_inactive.py
        id: python_script
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python .github/scripts/bulk_mark_inactive.py $GITHUB_EVENT_PATH

      - name: execute update_readmes.py
        id: python_script_readme
        run: python .github/scripts/update_readmes.py

      - name: commit files
        if: success()
        run: |
          git config --local user.email ${{ steps.python_script.outputs.commit_email }}
          git config --local user.name ${{ steps.python_script.outputs.commit_username }}
          git add .github/scripts/listings.json
          git add README.md
          git add README-Off-Season.md
          git diff-index --quiet HEAD || (git commit -a -m "${{ steps.python_script.outputs.commit_message }}" --allow-empty)

      - name: push changes
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev

      - name: Post Summary Comment
        run: |
          cat << 'EOF' > comment.txt
          ${{ steps.python_script.outputs.summary_comment }}
          EOF
          gh issue comment ${{ github.event.issue.number }} --body-file comment.txt
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Problem With Action
        run: gh issue comment ${{ github.event.issue.number }} --body "There was an error with our github action. Error - ${{ steps.python_script.outputs.error_message }} ${{ steps.python_script_readme.outputs.error_message }}"
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

